# Web Server Config
server:
  port: ${SPRING_PORT:8080}
  ssl:
    enabled: true
#    trust-store-password:
#    trust-store:
#    client-auth:
#    key-store-password:
#    key-password:
#    key-store:

# Spring App Config
spring:
  application:
    name: ${SPRING_APPNAME:springcloud-gateway}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # use netflix eureka discovery service
          lower-case-service-id: true # this is important to find service name due to case sensitivity

eureka:
  client:
    serviceUrl:
      defaultZone: http://${SPRING_EUREKA_SERVER:localhost}:${SPRING_EUREKA_PORT:8761}/eureka
    registry-fetch-interval-seconds: 3

